"""
Pydantic data models and schemas for API requests, responses, chunk representations, and evaluations.
"""

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class SourceCitation(BaseModel):
    """Structured citation referencing a knowledge base policy snippet."""
    document: str = Field(description="Name or title of the cited document")
    section: str = Field(description="Policy clause or section title")
    page: int = Field(description="Page number in the original document")
    snippet: str = Field(description="Verbatim supporting text snippet from the document")


class ChatMessage(BaseModel):
    """Single turn in a conversational dialogue."""
    role: Literal["user", "assistant", "system"] = Field(description="Speaker role")
    content: str = Field(description="Message text")


class QueryRequest(BaseModel):
    """Payload for customer support question answering."""
    query: str = Field(min_length=2, max_length=1000, description="Customer question or inquiry")
    conversation_id: Optional[str] = Field(default=None, description="Unique session identifier for multi-turn tracking")
    history: Optional[List[ChatMessage]] = Field(default=None, description="Prior conversational context for query expansion")
    top_k: Optional[int] = Field(default=3, ge=1, le=10, description="Number of context citations to return")


class QueryResponse(BaseModel):
    """Grounded customer answer payload with citations and confidence metrics."""
    answer: str = Field(description="Grounded response text generated by the assistant")
    sources: List[SourceCitation] = Field(default_factory=list, description="Array of source citations")
    confidence_score: float = Field(ge=0.0, le=1.0, description="Confidence score from 0.0 to 1.0")
    latency_ms: float = Field(description="End-to-end processing time in milliseconds")
    query_expanded: Optional[str] = Field(default=None, description="Decontextualized or expanded query used for retrieval")


class DocumentChunk(BaseModel):
    """Atomized chunk generated during document preprocessing."""
    chunk_id: str = Field(description="Unique SHA-256 or sequential chunk identifier")
    content: str = Field(description="Cleaned textual chunk content")
    doc_id: str = Field(description="Source document ID")
    doc_title: str = Field(description="Document title")
    section: str = Field(description="Section heading or clause identifier")
    page_no: int = Field(default=1, description="Page number where the chunk originates")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Arbitrary metadata attributes")


class IngestRequest(BaseModel):
    """Request payload to trigger knowledge base ingestion."""
    force_download: bool = Field(default=False, description="Re-download datasets from Google Drive even if cached locally")
    source: str = Field(default="all", description="Source selector: all | raw_pdfs | sample_json")


class IngestResponse(BaseModel):
    """Response payload following dataset ingestion."""
    status: str = Field(default="success")
    total_documents_ingested: int = Field(description="Count of processed document files")
    total_chunks_created: int = Field(description="Count of indexed chunks in the vector store")
    indexed_files: List[str] = Field(default_factory=list, description="List of processed filenames")
    message: str = Field(description="Summary message")


class FeedbackRequest(BaseModel):
    """User feedback for RAG generation quality."""
    query_id: Optional[str] = Field(default=None, description="Identifier of the query being reviewed")
    query: str = Field(description="Customer question")
    answer: str = Field(description="Assistant response")
    feedback: Literal["thumbs_up", "thumbs_down", "hallucination"] = Field(description="Feedback category")
    comments: Optional[str] = Field(default=None, description="Optional user commentary")


class FeedbackResponse(BaseModel):
    """Response acknowledging feedback submission."""
    status: str = Field(default="recorded")
    feedback_id: str = Field(description="Unique identifier for the stored feedback item")
    message: str = Field(description="Confirmation message")


class HealthResponse(BaseModel):
    """Health status and configuration overview of the running service."""
    status: str = Field(default="healthy")
    environment: str = Field(description="Active environment")
    total_chunks_indexed: int = Field(description="Number of chunks currently searchable")
    llm_provider: str = Field(description="Selected LLM provider")
    embedding_provider: str = Field(description="Selected embedding model provider")
    vector_store_type: str = Field(description="Selected vector database backend")
